from pathlib import Path
import unittest


class WebStaticTests(unittest.TestCase):
    def test_static_workbench_references_real_api_contracts(self) -> None:
        root = Path("web/dist")
        html = (root / "index.html").read_text(encoding="utf-8")
        js = (root / "app.js").read_text(encoding="utf-8")
        css = (root / "styles.css").read_text(encoding="utf-8")
        feishu_view = Path(
            "integrations/feishu-record-view/opportunity-view/src/index.tsx"
        ).read_text(encoding="utf-8")
        feishu_webpack = Path(
            "integrations/feishu-record-view/opportunity-view/webpack.config.js"
        ).read_text(encoding="utf-8")
        feishu_package = Path(
            "integrations/feishu-record-view/opportunity-view/package.json"
        ).read_text(encoding="utf-8")

        self.assertIn('id="runForm"', html)
        self.assertIn("/api/runs", js)
        self.assertIn("/api/outbox", js)
        self.assertIn("/api/subscriptions", js)
        self.assertIn("/api/sources", js)
        self.assertIn("/api/sources/alerts", js)
        self.assertIn("sendSourceAlertsToFeishu", js)
        self.assertIn("配置接收目标", js)
        self.assertIn("/api/evaluations/agent", js)
        self.assertIn("/api/memory/events", js)
        self.assertIn("/api/memory/weekly", js)
        self.assertIn("/api/memory/advice/", js)
        self.assertIn("data-advice-status", js)
        self.assertIn("/api/integrations/feishu/overview", js)
        self.assertIn('id="openFeishuBitableButton"', html)
        self.assertIn('id="opportunityTopicFilter"', html)
        self.assertIn('id="opportunitySortSelect"', html)
        self.assertIn('id="opportunityDetailDialog"', html)
        self.assertIn('id="opportunityDecisionBoard"', html)
        self.assertIn('id="sendOpportunityBriefingButton"', html)
        self.assertIn("bitableCheck.record_count", js)
        self.assertIn('query.set("topic", topic)', js)
        self.assertIn("openOpportunityDetail", js)
        self.assertIn("applyOpportunityAction", js)
        self.assertIn("data-opportunity-action", js)
        self.assertIn("qualification-gates", js)
        self.assertIn("data-opportunity-facts", js)
        self.assertIn("/facts", js)
        self.assertIn("/api/opportunities/${encodeURIComponent(noticeId)}/actions", js)
        self.assertIn("requirement_review", js)
        self.assertIn("historical_suppliers", js)
        self.assertIn("onSelectionChange", feishu_view)
        self.assertIn("verifyFacts", feishu_view)
        self.assertIn("const current = await currentRecord()", feishu_view)
        self.assertIn('channel: "feishu_record_view"', feishu_view)
        self.assertIn('method: "PATCH"', feishu_view)
        self.assertIn('"竞争情报"', feishu_view)
        self.assertIn('"需求覆盖率"', feishu_view)
        self.assertIn("new BitableAppWebpackPlugin({ open: false })", feishu_webpack)
        self.assertIn("process.env.NODE_ENV = argv.mode", feishu_webpack)
        self.assertNotIn('argv.mode === "development"', feishu_webpack)
        self.assertIn("opdev upload ./dist -t block", feishu_package)
        self.assertIn("/api/integrations/feishu/receiver", js)
        self.assertIn("/api/integrations/feishu/users?limit=100", js)
        self.assertIn('data-receive-type="open_id"', js)
        self.assertIn("授权成员", js)
        self.assertIn("/send-feishu", js)
        self.assertIn("/api/traces/", js)
        self.assertIn("/api/checkpoints/", js)
        self.assertIn('href="/logo.svg"', html)
        self.assertIn("Agent评测", html)
        self.assertIn("用户记忆", html)
        self.assertIn('id="runHistoryBody"', html)
        self.assertIn('id="subscriptionPageBody"', html)
        self.assertIn('id="evaluationSummary"', html)
        self.assertIn('id="evaluationHarnessCases"', html)
        self.assertIn('id="memorySummary"', html)
        self.assertNotIn('id="memoryDigest"', html)
        self.assertIn('id="memoryProfile"', html)
        self.assertIn('id="memoryGeneratedAdvice"', html)
        self.assertIn('id="smartStartPanel"', html)
        self.assertIn('id="smartStartMeta"', html)
        self.assertIn('id="feishuDeliveryInput"', html)
        self.assertIn('id="feishuFeatureList"', html)
        self.assertIn('id="feishuChatSelect"', html)
        self.assertIn('id="importFeishuLeadsButton"', html)
        self.assertIn("/api/integrations/feishu/bitable/import-leads", js)
        self.assertIn("importFeishuPartnerLeads", js)
        self.assertIn("partnerLeadImport.last_run", js)
        self.assertIn("features.fact_verification", js)
        self.assertIn('id="mobileNavButton"', html)
        self.assertIn("data-example-query", html)
        self.assertIn('id="refreshMemoryButton"', html)
        self.assertIn('id="saveMemoryButton"', html)
        self.assertNotIn('id="outboxSearchInput"', html)
        self.assertNotIn('id="outboxStatusFilter"', html)
        self.assertNotIn('id="outboxSortSelect"', html)
        self.assertNotIn('id="toggleOutboxButton"', html)
        self.assertIn('id="runSearchInput"', html)
        self.assertIn('id="runStatusFilter"', html)
        self.assertIn('id="runSortSelect"', html)
        self.assertIn('id="toggleRunsButton"', html)
        self.assertIn('id="notificationButton"', html)
        self.assertIn('id="notificationBadge"', html)
        self.assertIn('id="themeToggleButton"', html)
        self.assertIn('id="helpButton"', html)
        self.assertIn('id="userMenuButton"', html)
        self.assertIn('id="sourcePageList"', html)
        self.assertIn('id="sourceAlertSummary"', html)
        self.assertNotIn('id="sourceList"', html)
        self.assertNotIn('class="data-list subscription-list"', html)
        self.assertNotIn('class="data-list outbox-list"', html)
        self.assertNotIn('id="modelStatus"', html)
        self.assertNotIn('id="modelDoctorButton"', html)
        self.assertNotIn('id="modelDoctorResult"', html)
        self.assertNotIn("model-panel", html)
        self.assertIn('id="traceTimeline"', html)
        self.assertIn('id="checkpointList"', html)
        self.assertIn('id="stepEvidence"', html)
        self.assertIn('id="evidencePassedValue"', html)
        self.assertIn('id="attachmentsExtractedValue"', html)
        self.assertIn("data-delete-outbox-name", js)
        self.assertIn("data-delete-run-id", js)
        self.assertIn("data-delete-subscription-id", js)
        self.assertIn("data-popover-view", js)
        self.assertIn("ensureIntentReady", js)
        self.assertIn("clarificationQuestions", js)
        self.assertIn("needs-clarification", js)
        self.assertIn("refreshAll", js)
        self.assertIn("renderNotifications", js)
        self.assertIn("trackActivity", js)
        self.assertIn("renderMemory", js)
        self.assertIn("renderMemoryProfile", js)
        self.assertIn("renderGeneratedAdvice", js)
        self.assertIn("renderSmartStart", js)
        self.assertIn("renderFeishuOverview", js)
        self.assertIn("features.source_health_alert", js)
        self.assertIn("sourceAccessStatus", js)
        self.assertIn('label: "已登录"', js)
        self.assertIn("会话自然语言指令", js)
        self.assertIn("conversation_commands", js)
        self.assertIn("applyExampleQuery", js)
        self.assertIn("normalizeWorkbenchLayout", js)
        self.assertIn("source-health-grid", js)
        self.assertIn('login_expired: "登录过期"', js)
        self.assertIn("发现规则", js)
        self.assertIn("autoSelectActionMode", js)
        self.assertIn("hasScheduledIntent", js)
        self.assertIn("filterOutboxItems", js)
        self.assertIn("filterRunItems", js)
        self.assertIn("visibleListItems", js)
        self.assertIn("renderMemoryDigest", js)
        self.assertIn("renderSubscriptionCards", js)
        self.assertIn("subscriptionIncrementText", js)
        self.assertIn("last_skipped_sent", js)
        self.assertIn("next_run_at", js)
        self.assertIn("最近 Word", js)
        self.assertIn("fts_coverage_rate", js)
        self.assertIn("local_reuse_rate", js)
        self.assertIn("strict_recall_at_10", js)
        self.assertIn("strict_precision_at_10", js)
        self.assertIn('query.set("sort", sort)', js)
        self.assertIn("action_queue", js)
        self.assertIn("renderOpportunityDecisionBoard", js)
        self.assertIn("decision_sla_status", js)
        self.assertIn("/api/opportunities/escalations/send-feishu", js)
        self.assertIn("/api/opportunities/briefing/send-feishu", js)
        self.assertIn("sendOpportunityBriefing", js)
        self.assertIn("data-send-opportunity-escalations", js)
        self.assertIn("function opportunityPageSize", js)
        self.assertIn("vector_coverage_rate", js)
        self.assertNotIn("<span>3</span>", html)
        self.assertIn("evidence_passed", js)
        self.assertIn("attachments_extracted", js)
        self.assertIn(".workbench-grid", css)
        self.assertIn("align-items: start", css)
        self.assertIn(".history-detail-grid", css)
        self.assertIn(".eval-card", css)
        self.assertIn(".list-tools", css)
        self.assertIn(".list-hint", css)
        self.assertIn(".insight-row", css)
        self.assertIn(".profile-row", css)
        self.assertIn(".advice-action", css)
        self.assertIn(".priority-badge", css)
        self.assertIn(".smart-start", css)
        self.assertIn(".smart-card", css)
        self.assertIn(".opportunity-detail-dialog", css)
        self.assertIn(".opportunity-facts-form", css)
        self.assertIn(".requirement-dimensions", css)
        self.assertIn(".opportunity-decision-board", css)
        self.assertIn(".qualification-gates", css)
        self.assertIn(".qualification-decision-actions", css)
        self.assertIn(".feishu-center", css)
        self.assertIn(".mobile-nav-button", css)
        self.assertIn(".source-health-grid", css)
        self.assertIn(".source-rule-line", css)
        self.assertIn(".main-stack", css)
        self.assertIn(".data-list", css)
        self.assertIn(".data-row", css)
        self.assertIn(".data-actions", css)
        self.assertIn(".table-subvalue", css)
        self.assertIn('aria-disabled="true"', css)
        self.assertIn("overflow-x: hidden", css)
        self.assertIn("table-layout: fixed", css)
        self.assertNotIn("min-width: 850px", css)
        self.assertIn("body.theme-dark", css)
        self.assertIn(".clarify-chip", css)
        self.assertIn("white-space: normal", css)
        self.assertIn("overflow-y: auto", css)
        self.assertIn("grid-template-rows: minmax(280px, 42vh) auto", css)


if __name__ == "__main__":
    unittest.main()
