from pathlib import Path
import unittest


class WebStaticTests(unittest.TestCase):
    def test_demo_reliability_console_exposes_live_history_replay_and_layout_audit(self) -> None:
        root = Path("web/dist")
        html = (root / "index.html").read_text(encoding="utf-8")
        js = (root / "app.js").read_text(encoding="utf-8")
        css = (root / "styles.css").read_text(encoding="utf-8")

        self.assertIn('data-view="demoConsoleView">演示控制台', html)
        self.assertIn('id="demoConsoleView"', html)
        self.assertIn("实时动作", html)
        self.assertIn("已验证历史", html)
        self.assertIn("同版本真实回放", html)
        self.assertIn('id="demoEnvironmentChecks"', html)
        self.assertIn('id="demoCaseGrid"', html)
        self.assertIn('id="demoLayoutAuditButton"', html)
        self.assertIn('id="demoRehearsalLog"', html)
        self.assertIn("/api/demo-reliability", js)
        self.assertIn("runThreeDemoRehearsals", js)
        self.assertIn("runDemoLayoutAuditProfile", js)
        self.assertIn('frame.style.width = `${width}px`', js)
        self.assertIn('frame.style.height = `${height}px`', js)
        self.assertIn("critical_overflows", js)
        self.assertIn("data-demo-case-id", js)
        self.assertIn("demo-console-shell", css)
        self.assertIn("demo-mode-badge", css)
        self.assertIn("demo-event-row", css)
        self.assertIn("@media (max-width: 1100px)", css)
        self.assertIn("@media (max-width: 760px)", css)

    def test_judge_live_challenge_has_a_direct_auditable_entry(self) -> None:
        root = Path("web/dist")
        html = (root / "index.html").read_text(encoding="utf-8")
        js = (root / "app.js").read_text(encoding="utf-8")
        css = (root / "styles.css").read_text(encoding="utf-8")

        self.assertIn('data-view="challengeView">评委挑战', html)
        self.assertIn('id="challengeView"', html)
        self.assertIn('id="challengeForm"', html)
        self.assertIn('id="challengeCategory"', html)
        self.assertIn('id="challengeRegion"', html)
        self.assertIn('id="challengeTimeWindow"', html)
        self.assertIn('id="challengeKeyword"', html)
        self.assertIn("本地索引优先", html)
        self.assertIn("联网状态不隐瞒", html)
        self.assertIn("全程自动留痕", html)
        self.assertIn("/api/live-challenges", js)
        self.assertIn("/supplement`,", js)
        self.assertIn("/cancel`,", js)
        self.assertIn("?view=challengeView", js)
        self.assertIn("data-challenge-opportunity", js)
        self.assertIn("challenge-source-state", css)
        self.assertIn("challenge-result-card", css)
        self.assertIn("@media (max-width: 640px)", css)

    def test_workspace_presentation_layer_is_loaded_after_component_styles(self) -> None:
        root = Path("web/dist")
        html = (root / "index.html").read_text(encoding="utf-8")
        css = (root / "workspace.css").read_text(encoding="utf-8")
        self.assertLess(html.index('/styles.css'), html.index('/workspace.css'))
        self.assertIn('id="queryTitle"', html)
        self.assertIn('[hidden] { display: none !important; }', css)
        self.assertIn(':focus-visible', css)
        self.assertIn('prefers-reduced-motion', css)
        self.assertIn('body.theme-dark', css)

    def test_static_workbench_references_real_api_contracts(self) -> None:
        root = Path("web/dist")
        html = (root / "index.html").read_text(encoding="utf-8")
        js = (root / "app.js").read_text(encoding="utf-8")
        css = (root / "styles.css").read_text(encoding="utf-8")
        feishu_view = Path(
            "integrations/feishu-record-view/opportunity-view/src/index.tsx"
        ).read_text(encoding="utf-8")
        feishu_styles = Path(
            "integrations/feishu-record-view/opportunity-view/src/styles.css"
        ).read_text(encoding="utf-8")
        feishu_webpack = Path(
            "integrations/feishu-record-view/opportunity-view/webpack.config.js"
        ).read_text(encoding="utf-8")
        feishu_package = Path(
            "integrations/feishu-record-view/opportunity-view/package.json"
        ).read_text(encoding="utf-8")

        self.assertIn('id="runForm"', html)
        self.assertIn("/api/runs", js)
        self.assertIn("/api/outbox", js)
        self.assertIn("/api/subscriptions", js)
        self.assertIn("/api/sources", js)
        self.assertIn("/api/sources/alerts", js)
        self.assertIn("sendSourceAlertsToFeishu", js)
        self.assertIn("createSourceIncidentTask", js)
        self.assertIn("/api/sources/alerts/create-feishu-task", js)
        self.assertIn("syncSourceIncidentTasks", js)
        self.assertIn("/api/sources/incidents/sync", js)
        self.assertIn("verification_failed", js)
        self.assertIn("verifyQianlimaLogin", js)
        self.assertIn("/api/sources/qianlima/verify", js)
        self.assertIn("source-recovery", css)
        self.assertIn("sourceFailureSummary", js)
        self.assertIn("source-recovered-line", css)
        self.assertIn("配置接收目标", js)
        self.assertIn("/api/evaluations/agent", js)
        self.assertIn("/api/memory/events", js)
        self.assertIn("/api/memory/weekly", js)
        self.assertIn("/api/memory/advice/", js)
        self.assertIn("data-advice-status", js)
        self.assertIn("/api/integrations/feishu/overview", js)
        self.assertIn('id="openFeishuBitableButton"', html)
        self.assertIn('id="opportunityTopicFilter"', html)
        self.assertIn('id="opportunitySortSelect"', html)
        self.assertIn('id="opportunityDetailDialog"', html)
        self.assertIn('id="opportunityOutcomeDialog"', html)
        self.assertIn('id="opportunityDecisionBoard"', html)
        self.assertIn('id="sendOpportunityBriefingButton"', html)
        self.assertIn('id="sendOpportunityChangesButton"', html)
        self.assertIn("bitableCheck.record_count", js)
        self.assertIn('query.set("topic", topic)', js)
        self.assertIn("openOpportunityDetail", js)
        self.assertIn("/digital-twin", js)
        self.assertIn("投标数字孪生 · 动态项目档案", js)
        self.assertIn("为什么是", js)
        self.assertIn("scheduleDigitalTwinRefresh", js)
        self.assertIn("招标数字档案", html)
        self.assertIn("数字档案", js)
        self.assertIn("loadOpportunityRevisionHistory", js)
        self.assertIn("/api/opportunities/changes?notice_id=", js)
        self.assertIn("noticeChangeImpacts", js)
        self.assertIn("applyOpportunityAction", js)
        self.assertIn("data-opportunity-action", js)
        self.assertIn("item.action_contract?.actions", js)
        self.assertIn("requires_outcome", js)
        self.assertIn("submitOpportunityOutcome", js)
        self.assertIn("/outcome`,", js)
        self.assertNotIn('if (stage === "identified") add("claim"', js)
        self.assertIn("qualification-gates", js)
        self.assertIn("data-opportunity-facts", js)
        self.assertIn("/facts", js)
        self.assertIn("投标要求账本", js)
        self.assertIn("loadOpportunityRequirements", js)
        self.assertIn("data-opportunity-requirements-form", js)
        self.assertIn("/requirements`,", js)
        self.assertIn("extractOpportunityRequirements", js)
        self.assertIn("/requirements/extract", js)
        self.assertIn("/bid-workplan/build", js)
        self.assertIn("data-bid-workplan", js)
        self.assertIn("RACI 责任矩阵", js)
        self.assertIn("缺口泳道", js)
        self.assertIn("报价计划", js)
        self.assertIn("opportunity-requirement-impact", js)
        self.assertIn("impactsByRequirementId", js)
        self.assertIn("review_status_label ||", js)
        self.assertIn("loadOpportunityWarRoomPlan", js)
        self.assertIn("/war-room${workspaceQuery}", js)
        self.assertIn("data-launch-war-room", js)
        self.assertIn("/war-room/launch", js)
        self.assertIn("一键投标战情室", js)
        self.assertIn("war-room-journey", js)
        self.assertIn("data-retry-war-room-step", js)
        self.assertIn("/war-room/sync-back", js)
        self.assertIn("/war-room/dispatch-changes", js)
        self.assertIn("/war-room/archive", js)
        self.assertIn("loadOpportunityCollaborationNotes", js)
        self.assertIn("/collaboration-notes", js)
        self.assertIn("loadOpportunityReviewBoard", js)
        self.assertIn("/review-board", js)
        self.assertIn("openRequestedOpportunity", js)
        self.assertIn("/api/opportunities/${encodeURIComponent(noticeId)}", js)
        self.assertIn("data-sync-review-board", js)
        self.assertIn("data-run-review-agents", js)
        self.assertIn("runOpportunityReviewAgents", js)
        self.assertIn("可质询多角色会审", js)
        self.assertIn("专业对手盘", js)
        self.assertIn("投标决策沙盘", js)
        self.assertIn("基准与模拟双舱", js)
        self.assertIn("不输出中标概率", js)
        self.assertIn("data-decision-sandbox-form", js)
        self.assertIn("data-compare-decision-scenarios", js)
        self.assertIn("/decision-sandbox", js)
        self.assertIn("data-retry-review-agent", js)
        self.assertIn("reviewAgentOpinionCard", js)
        self.assertIn("review-agent-evidence-ids", css)
        self.assertIn("review-agent-runs", css)
        self.assertIn("guarded_case_count", js)
        self.assertIn("证据安全门禁", js)
        self.assertIn("is-evidence-guarded", css)
        self.assertIn("data-send-review-board-feishu", js)
        self.assertIn("sendOpportunityReviewBoardToFeishu", js)
        self.assertIn("/review-board/send-feishu", js)
        self.assertIn("opportunity-journey", js)
        self.assertIn("renderOpportunityJourney", js)
        self.assertIn("暂无待裁决项", js)
        self.assertIn("data-scroll-opportunity-target", js)
        self.assertIn("opportunityChangeSection", js)
        self.assertIn("opportunityRequirementsSection", js)
        self.assertIn("opportunityReviewSection", js)
        self.assertIn("opportunityCollaborationSection", js)
        self.assertIn("/api/opportunities/${encodeURIComponent(noticeId)}/actions", js)
        self.assertIn("item.change_summary", js)
        self.assertIn("noticeChangeFieldLabel", js)
        self.assertIn("item.change_review", js)
        self.assertIn("change_review_overdue", js)
        self.assertIn("requirement_review", js)
        self.assertIn("historical_suppliers", js)
        self.assertIn("onSelectionChange", feishu_view)
        self.assertIn("acknowledge_change", feishu_view)
        self.assertIn("verifyFacts", feishu_view)
        self.assertIn("const current = await currentRecord()", feishu_view)
        self.assertIn("bitable.bridge.getBaseUserId", feishu_view)
        self.assertIn("requires_member_identity", feishu_view)
        self.assertNotIn("function workflowActions", feishu_view)
        self.assertIn("/facts`).catch", feishu_view)
        self.assertIn("/actions`,", feishu_view)
        self.assertIn('channel: "feishu_record_view"', feishu_view)
        self.assertIn("发送认领卡", feishu_view)
        self.assertIn('method: "PATCH"', feishu_view)
        self.assertIn('"竞争情报"', feishu_view)
        self.assertIn('"需求覆盖率"', feishu_view)
        self.assertIn(".workflow-grid", feishu_styles)
        self.assertIn(".workflow-blockers", feishu_styles)
        self.assertIn(".outcome-section", feishu_styles)
        self.assertIn("new BitableAppWebpackPlugin({ open: false })", feishu_webpack)
        self.assertIn("process.env.NODE_ENV = argv.mode", feishu_webpack)
        self.assertNotIn('argv.mode === "development"', feishu_webpack)
        self.assertIn("opdev upload ./dist -t block", feishu_package)
        self.assertIn("/api/integrations/feishu/receiver", js)
        self.assertIn("/api/integrations/feishu/users?limit=100", js)
        self.assertIn('data-receive-type="open_id"', js)
        self.assertIn("授权成员", js)
        self.assertIn("/send-feishu", js)
        self.assertIn("/team", js)
        self.assertIn("opportunity-team-list", css)
        self.assertIn("/stakeholders", js)
        self.assertIn("stakeholder-matrix", css)
        self.assertIn("/relationship-actions", js)
        self.assertIn('id="relationshipActionDialog"', html)
        self.assertIn("relationship-action-matrix", css)
        self.assertIn("relationship_actions", feishu_view)
        self.assertIn("submitOutcome", feishu_view)
        self.assertIn("outcomeActions", feishu_view)
        self.assertIn("requires_outcome", feishu_view)
        self.assertIn("/api/traces/", js)
        self.assertIn("/api/checkpoints/", js)
        self.assertIn('href="/logo.svg"', html)
        self.assertIn("评测与价值", html)
        self.assertIn("业务价值实验室", html)
        self.assertIn("同一批公开文件", html)
        self.assertIn("辅助等待（秒）", html)
        self.assertIn("人工金标入口", html)
        self.assertIn("价值链覆盖", html)
        self.assertIn("现场检索挑战", html)
        self.assertIn("合作方尽调", html)
        self.assertIn("情景训练演练", html)
        self.assertIn("businessDirectionCoverage", js)
        self.assertIn("businessMetricCard", js)
        self.assertIn("businessValuePercent", js)
        self.assertIn("baseline_omissions", js)
        self.assertIn("gold_standard_url", js)
        self.assertIn("business-value-lab", css)
        self.assertIn("business-direction-item", css)
        self.assertIn("business-sample-row", css)
        self.assertIn("用户记忆", html)
        self.assertIn('id="runHistoryBody"', html)
        self.assertIn('id="subscriptionPageBody"', html)
        self.assertIn('id="evaluationSummary"', html)
        self.assertIn('id="evaluationHarnessCases"', html)
        self.assertIn('id="goldAnnotationDialog"', html)
        self.assertIn('id="goldAnnotationSourceUrl"', html)
        self.assertIn("data-annotate-gold-case", js)
        self.assertIn("submitGoldAnnotation", js)
        self.assertIn("/api/evaluations/gold/cases/", js)
        self.assertIn("gold-annotation-grid", css)
        self.assertIn('id="memorySummary"', html)
        self.assertIn('id="organizationView"', html)
        self.assertIn('id="organizationWorkspaceSelect"', html)
        self.assertIn('id="openOrganizationWorkspaceButton"', html)
        self.assertIn('id="organizationGroupDialog"', html)
        self.assertIn('id="organizationConvertDialog"', html)
        self.assertIn('id="organizationReportDelivery"', html)
        self.assertIn("企业投标记忆体", html)
        self.assertIn('id="bidMemoryDashboard"', html)
        self.assertIn("renderBidMemoryGraph", js)
        self.assertIn("相似项目与经验推荐", js)
        self.assertIn("永不生成伪胜率", js)
        self.assertIn("data-archive-bid-memory", js)
        self.assertIn("/bid-memory/archive", js)
        self.assertIn("/bid-memory/assets/", js)
        self.assertIn(".bid-memory-cockpit", css)
        self.assertIn(".bid-memory-node.type-target", css)
        self.assertIn('id="radarView"', html)
        self.assertIn("全国与全球机会雷达", html)
        self.assertIn('id="radarMap"', html)
        self.assertIn("数据源可信度地图", html)
        self.assertIn("renderOpportunityRadar", js)
        self.assertIn("radarWorldBackground", js)
        self.assertIn("radarChinaBackground", js)
        self.assertIn("/api/opportunity-radar", js)
        self.assertIn("data-radar-query-location", js)
        self.assertIn("radar-motion-off", css)
        self.assertIn("radar-presentation", css)
        self.assertNotIn('id="memoryDigest"', html)
        self.assertIn('id="memoryProfile"', html)
        self.assertIn('id="memoryGeneratedAdvice"', html)
        self.assertIn('id="smartStartPanel"', html)
        self.assertIn('id="smartStartMeta"', html)
        self.assertIn('id="feishuDeliveryInput"', html)
        self.assertIn('id="feishuDeliveryWorkspace"', html)
        self.assertIn("renderFeishuDeliveryWorkspaceOptions", js)
        self.assertIn("feishu_workspace_id", js)
        self.assertIn("delivery-workspace", css)
        self.assertIn('id="feishuFeatureList"', html)
        self.assertIn('id="feishuChatSelect"', html)
        self.assertIn('id="importFeishuLeadsButton"', html)
        self.assertIn("/api/integrations/feishu/bitable/import-leads", js)
        self.assertIn("importFeishuPartnerLeads", js)
        self.assertIn("partnerLeadImport.last_run", js)
        self.assertIn("features.fact_verification", js)
        self.assertIn('id="mobileNavButton"', html)
        self.assertIn("data-example-query", html)
        self.assertIn('id="refreshMemoryButton"', html)
        self.assertIn('id="saveMemoryButton"', html)
        self.assertIn("workspace.feishu_chat_url", js)
        self.assertIn("群内通知已发送", js)
        self.assertNotIn('id="outboxSearchInput"', html)
        self.assertNotIn('id="outboxStatusFilter"', html)
        self.assertNotIn('id="outboxSortSelect"', html)
        self.assertNotIn('id="toggleOutboxButton"', html)
        self.assertIn('id="runSearchInput"', html)
        self.assertIn('id="runStatusFilter"', html)
        self.assertIn('id="runSortSelect"', html)
        self.assertIn('id="toggleRunsButton"', html)
        self.assertIn('id="notificationButton"', html)
        self.assertIn('id="notificationBadge"', html)
        self.assertIn('id="themeToggleButton"', html)
        self.assertIn('id="helpButton"', html)
        self.assertIn('id="userMenuButton"', html)
        self.assertIn('id="sourcePageList"', html)
        self.assertIn('id="sourceAlertSummary"', html)
        self.assertNotIn('id="sourceList"', html)
        self.assertNotIn('class="data-list subscription-list"', html)
        self.assertNotIn('class="data-list outbox-list"', html)
        self.assertNotIn('id="modelStatus"', html)
        self.assertNotIn('id="modelDoctorButton"', html)
        self.assertNotIn('id="modelDoctorResult"', html)
        self.assertNotIn("model-panel", html)
        self.assertIn('id="traceTimeline"', html)
        self.assertIn('id="checkpointList"', html)
        self.assertIn('id="stepEvidence"', html)
        self.assertIn('id="evidencePassedValue"', html)
        self.assertIn('id="attachmentsExtractedValue"', html)
        self.assertIn("data-delete-outbox-name", js)
        self.assertIn("data-delete-run-id", js)
        self.assertIn("data-delete-subscription-id", js)
        self.assertIn("data-popover-view", js)
        self.assertIn("ensureIntentReady", js)
        self.assertIn("clarificationQuestions", js)
        self.assertIn("needs-clarification", js)
        self.assertIn("data-confirm-intent", js)
        self.assertIn("intent-clarification", css)
        self.assertIn("refreshAll", js)
        self.assertIn("renderNotifications", js)
        self.assertIn("trackActivity", js)
        self.assertIn("renderMemory", js)
        self.assertIn("refreshOrganizationWorkspaces", js)
        self.assertIn("saveOrganizationMemory", js)
        self.assertIn("submitOrganizationGroup", js)
        self.assertIn("submitOrganizationConversion", js)
        self.assertIn("renderOrganizationReportDelivery", js)
        self.assertIn("sendWorkspaceReport", js)
        self.assertIn("data-send-workspace-report", js)
        self.assertIn("/outbox/${encodeURIComponent(filename)}/send-feishu", js)
        self.assertIn("/api/organization/workspaces", js)
        self.assertIn("organization-command-guide", js)
        self.assertIn("项目意见 机会编号：内容", js)
        self.assertIn("会审意见 机会编号 要求编号：内容", js)
        self.assertIn("saveHumanReviewOpinion", js)
        self.assertIn("human_opinions", js)
        self.assertIn("renderMemoryProfile", js)
        self.assertIn("renderGeneratedAdvice", js)
        self.assertIn("renderSmartStart", js)
        self.assertIn("renderFeishuOverview", js)
        self.assertIn("features.source_health_alert", js)
        self.assertIn("features.source_incident_task", js)
        self.assertIn("sourceAccessStatus", js)
        self.assertIn('label: "已登录"', js)
        self.assertIn("health.last_failure_at", js)
        self.assertIn("会话自然语言指令", js)
        self.assertIn("conversation_commands", js)
        self.assertIn("listener.running", js)
        self.assertIn("applyExampleQuery", js)
        self.assertIn("normalizeWorkbenchLayout", js)
        self.assertIn("source-health-grid", js)
        self.assertIn('login_expired: "登录过期"', js)
        self.assertIn("发现规则", js)
        self.assertIn("autoSelectActionMode", js)
        self.assertIn("hasScheduledIntent", js)
        self.assertIn("filterOutboxItems", js)
        self.assertIn("filterRunItems", js)
        self.assertIn("visibleListItems", js)
        self.assertIn("renderMemoryDigest", js)
        self.assertIn("renderSubscriptionCards", js)
        self.assertIn("subscriptionIncrementText", js)
        self.assertIn("last_skipped_sent", js)
        self.assertIn("next_run_at", js)
        self.assertIn("最近 Word", js)
        self.assertIn("fts_coverage_rate", js)
        self.assertIn("local_reuse_rate", js)
        self.assertIn("strict_recall_at_10", js)
        self.assertIn("strict_precision_at_10", js)
        self.assertIn('query.set("sort", sort)', js)
        self.assertIn("action_queue", js)
        self.assertIn("renderOpportunityDecisionBoard", js)
        self.assertIn("opportunityNextWork", js)
        self.assertIn("decision-priority-item", js)
        self.assertIn("decision_sla_status", js)
        self.assertIn("/api/opportunities/escalations/send-feishu", js)
        self.assertIn("/api/opportunities/briefing/send-feishu", js)
        self.assertIn("/api/opportunities/changes/send-feishu", js)
        self.assertIn("sendOpportunityBriefing", js)
        self.assertIn("data-send-opportunity-escalations", js)
        self.assertIn("function opportunityPageSize", js)
        self.assertIn("vector_coverage_rate", js)
        self.assertNotIn("<span>3</span>", html)
        self.assertIn("evidence_passed", js)
        self.assertIn("attachments_extracted", js)
        self.assertIn(".workbench-grid", css)
        self.assertIn("align-items: start", css)
        self.assertIn(".decision-priority-item", css)
        self.assertIn(".opportunity-journey", css)
        self.assertIn(".history-detail-grid", css)
        self.assertIn(".eval-card", css)
        self.assertIn(".list-tools", css)
        self.assertIn(".list-hint", css)
        self.assertIn(".insight-row", css)
        self.assertIn(".profile-row", css)
        self.assertIn(".advice-action", css)
        self.assertIn(".organization-report-delivery", css)
        self.assertIn(".priority-badge", css)
        self.assertIn(".smart-start", css)
        self.assertIn(".organization-layout", css)
        self.assertIn(".organization-memory-row", css)
        self.assertIn(".organization-convert-grid", css)
        self.assertIn(".smart-card", css)
        self.assertIn(".opportunity-detail-dialog", css)
        self.assertIn(".digital-twin-cockpit", css)
        self.assertIn(".digital-twin-score-grid", css)
        self.assertIn(".digital-twin-flow", css)
        self.assertIn("来源可信关系", js)
        self.assertIn("/source-relations", js)
        self.assertIn("renderSourceRelationGraph", js)
        self.assertIn("data-source-relation-decision", js)
        self.assertIn("拆分并锁定", js)
        self.assertIn(".source-relation-shell", css)
        self.assertIn(".source-relation-graph", css)
        self.assertIn(".source-relation-conflicts", css)
        self.assertIn(".decision-sandbox-shell", css)
        self.assertIn(".sandbox-dual-cockpit", css)
        self.assertIn(".decision-sandbox-impact-grid", css)
        self.assertIn('id="evidenceMicroscopeDialog"', html)
        self.assertIn("/evidence-microscope", js)
        self.assertIn("data-open-evidence-microscope", js)
        self.assertIn("renderEvidenceMicroscope", js)
        self.assertIn("renderHighlightedEvidence", js)
        self.assertIn("为什么不同意", js)
        self.assertIn("规则证据审阅", js)
        self.assertIn(".evidence-microscope-dialog", css)
        self.assertIn(".evidence-chain-visual", css)
        self.assertIn(".evidence-split-view", css)
        self.assertIn(".opportunity-outcome-dialog", css)
        self.assertIn(".opportunity-facts-form", css)
        self.assertIn(".opportunity-requirement-ledger", css)
        self.assertIn(".requirement-dimensions", css)
        self.assertIn(".opportunity-decision-board", css)
        self.assertIn(".opportunity-change-list", css)
        self.assertIn(".opportunity-revision-history", css)
        self.assertIn(".change-impact-grid", css)
        self.assertIn(".war-room-plan", css)
        self.assertIn(".war-room-command-head", css)
        self.assertIn(".war-room-journey", css)
        self.assertIn(".war-room-resource-grid", css)
        self.assertIn(".war-room-receipt-list", css)
        self.assertIn(".collaboration-note-form", css)
        self.assertIn(".requirement-review-board", css)
        self.assertIn(".review-agent-panel", css)
        self.assertIn(".change-review-status", css)
        self.assertIn(".qualification-gates", css)
        self.assertIn(".qualification-decision-actions", css)
        self.assertIn(".feishu-center", css)
        self.assertIn(".mobile-nav-button", css)
        self.assertIn(".source-health-grid", css)
        self.assertIn(".source-rule-line", css)
        self.assertIn(".main-stack", css)
        self.assertIn(".main-stack > .chat-panel", css)
        self.assertIn(".main-stack > .chat-panel .chat-stream", css)
        self.assertIn("grid-template-rows: minmax(370px, min(40vh, 400px)) auto", css)
        self.assertIn("max-height: min(40vh, 400px)", css)
        self.assertIn('id="workbenchContext"', html)
        self.assertIn("renderWorkbenchContext", js)
        self.assertIn(".workbench-context", css)
        self.assertIn(".data-list", css)
        self.assertIn(".data-row", css)
        self.assertIn(".data-actions", css)
        self.assertIn(".table-subvalue", css)
        self.assertIn('aria-disabled="true"', css)
        self.assertIn("overflow-x: hidden", css)
        self.assertIn("table-layout: fixed", css)
        self.assertNotIn("min-width: 850px", css)
        self.assertIn("body.theme-dark", css)
        self.assertIn(".clarify-chip", css)
        self.assertIn("white-space: normal", css)
        self.assertIn("overflow-y: auto", css)
        self.assertIn("grid-template-rows: minmax(280px, 42vh) auto", css)

    def test_direction_fifteen_visual_system_has_runtime_acceptance_contract(self) -> None:
        root = Path(__file__).resolve().parents[1]
        html = (root / "web" / "dist" / "index.html").read_text(encoding="utf-8")
        js = (root / "web" / "dist" / "app.js").read_text(encoding="utf-8")
        css = (root / "web" / "dist" / "styles.css").read_text(encoding="utf-8")

        for token in (
            "--tt-verified", "--tt-review", "--tt-gap", "--tt-system", "--tt-human",
            "--tt-font-status", "--tt-motion-productive", "--tt-motion-expressive",
        ):
            self.assertIn(token, css)
        self.assertIn('id="motionToggleButton"', html)
        self.assertIn('id="presentationModeButton"', html)
        self.assertIn('id="visualAuditButton"', html)
        self.assertIn('id="visualAuditResults"', html)
        self.assertIn("semanticStateTag", js)
        self.assertIn("renderVisualIdentityStrip", js)
        self.assertIn("runVisualSystemAuditProfile", js)
        self.assertIn("/api/visual-system/audits", js)
        self.assertIn("getComputedStyle", js)
        self.assertIn("critical_overflows", js)
        self.assertIn("min_status_font_px", js)
        self.assertIn("autoVisualAudit", js)
        self.assertIn('"projector_1440", 1440, 900', js)
        self.assertIn('"full_hd_1920", 1920, 1080', js)
        self.assertIn(":focus-visible", css)
        self.assertIn(".presentation-mode", css)
        self.assertIn("@media (min-width: 1600px)", css)
        self.assertIn("@media (max-width: 1500px)", css)
        self.assertIn("@media (prefers-reduced-motion: reduce)", css)
        self.assertIn(".motion-disabled *", css)
        self.assertIn(".radar-rings i,", css)
        self.assertIn("animation: none", css)

    def test_direction_eighteen_training_center_has_auditable_contract(self) -> None:
        root = Path(__file__).resolve().parents[1]
        html = (root / "web" / "dist" / "index.html").read_text(encoding="utf-8")
        js = (root / "web" / "dist" / "app.js").read_text(encoding="utf-8")
        css = (root / "web" / "dist" / "styles.css").read_text(encoding="utf-8")

        for token in (
            'data-view="trainingView">训练',
            'id="trainingView"',
            'id="trainingScenarioList"',
            'id="trainingSetupForm"',
            'id="trainingPhaseRail"',
            'id="trainingStage"',
            'id="trainingReport"',
            'id="trainingEvidenceList"',
            'id="trainingTeamReadiness"',
            'id="trainingHistory"',
        ):
            self.assertIn(token, html)
        for phase in ("开场", "基础事实", "证据追问", "风险变化", "行动计划", "总结"):
            self.assertIn(phase, html)
        self.assertIn("准备模式 · 不提前给答案", html)
        self.assertIn("学习模式 · 分层提示", html)
        self.assertIn("模拟回答和场景变化不会写回正式公告", html)
        for endpoint in (
            "/api/training/scenarios",
            "/api/training/sessions",
            "/api/training/team-readiness",
            "/recompute",
            "/sync-feishu",
        ):
            self.assertIn(endpoint, js)
        self.assertIn("FIVE-DIMENSION REPORT", js)
        self.assertIn("展开完整训练回放", js)
        self.assertIn("正式项目写入", js)
        self.assertIn("state.trainingSession = null", js)
        self.assertIn(".training-command", css)
        self.assertIn(".training-phase-rail", css)
        self.assertIn(".training-replay", css)
        self.assertIn("@media (max-width: 1250px)", css)
        self.assertIn("@media (max-width: 900px)", css)
        self.assertIn("@media (max-width: 560px)", css)
        self.assertIn("@media (prefers-reduced-motion: reduce)", css)

    def test_national_finals_home_connects_the_product_story_without_hiding_tools(self) -> None:
        root = Path(__file__).resolve().parents[1]
        html = (root / "web" / "dist" / "index.html").read_text(encoding="utf-8")
        js = (root / "web" / "dist" / "app.js").read_text(encoding="utf-8")
        css = (root / "web" / "dist" / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="finalsHomeView" class="view active"', html)
        self.assertIn("从公开机会，到可执行的投标决策", html)
        for label in ("机会", "项目", "企业", "战情图", "训练", "协作"):
            self.assertIn(f">{label}</button>", html)
        self.assertIn("<summary>更多工具</summary>", html)
        for tool in ("检索工作台", "评委挑战", "演示控制台", "数据源", "评测与价值", "设置"):
            self.assertIn(tool, html)
        for section in ("发现机会", "判断局面", "进入行动", "四层架构", "7-MINUTE ROUTE", "DATA FEASIBILITY"):
            self.assertIn(section, html)
        for identifier in (
            "finalsHomeIntentForm",
            "finalsHomeOpportunityCount",
            "finalsHomeScoreGrid",
            "finalsHomeActions",
            "finalsHomeSourceBoundary",
        ):
            self.assertIn(f'id="{identifier}"', html)
        self.assertIn("refreshFinalsHome", js)
        self.assertIn("/api/demo-reliability?compact=true", js)
        self.assertIn("routeFinalsIntent", js)
        self.assertIn("openFinalsPrimaryCase", js)
        self.assertIn(".finals-home-shell", css)
        self.assertIn(".finals-architecture-flow", css)
        self.assertIn(".finals-roadshow-route", css)
        self.assertIn("@media (max-width: 980px)", css)
        self.assertIn("@media (max-width: 620px)", css)
        self.assertIn("@media (prefers-reduced-motion: reduce)", css)


if __name__ == "__main__":
    unittest.main()
